version: "3.8"
services:
  app:
    container_name: app
    build:
      dockerfile: ./build/Dockerfile
      context: .
    environment:
      DBURL: "postgres://booksuser:p@ssw0rd123@database:5432/books?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: booksuser
      POSTGRES_PASSWORD: p@ssw0rd123
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: